####################################################
########## Author:          Rahul Gupta ############
########## Created At:      15-09-2022  ############
########## Last Updated At: 25-05-2023  ############
####################################################

name: "Validate Pull Requests"

# setting the trigger point of this workflow
on:
  # workflow will run on pull request generation
  pull_request:
    branches: [targetBranch,sourceBranch]
    
  # run workflow from "Actions" tab
  workflow_dispatch:

# define the jobs
jobs:

  # build the staging org
  build:
    runs-on: ubuntu-latest

    # pass docker hub credentials to load the dependencies
    container:
      image: ckrahulgupta/cfa-automated-deployment-image:latest

    # define the steps for validation
    steps:
          
      # perform code checkout so that github actions can access it
      - name: "Code Checkout"
        uses: actions/checkout@v2


      # process initialization
      - name: "Initialize Build"
        run: chmod +x ./.github/scripts/coe--init-build.sh && ./.github/scripts/coe--init-build.sh
        shell: bash

      # check code sanity
      - name: "Check Code Sanity"
        run: chmod +x ./.github/scripts/coe--sanity-check.sh && ./.github/scripts/coe--sanity-check.sh
        shell: bash

  